### ISSUE TITLE
Mention on fortran-lang?

### ISSUE THREAD

**Issue by Beliavsky** [ipqa-research/fortran-setup#1]
Not an "issue" but a question -- would you consider announcing this script on Fortran Discourse? Or would you mind if I do so? It's nice to be able install a whole suite of Fortran-related tools with one script. I added your project to my list of Fortran tools at https://github.com/Beliavsky/Fortran-Tools .

**Comment by fedebenelli** [comment]
Thanks for noticing this! 
I will gladly announce it on the Discourse! This project originated as a simple script to work with our teams with some "standard" configuration, but it should be easily extendable to include more cases (right now it only works on a Debian-based distribution -either WSL or not-). I will translate the texts in the script to English and then publish it at fortran-lang :)
